export const foods = [
  {
    id: 1,
    name: '湘西腊肉',
    category: 'main',
    tags: ['土家族', '传统名菜', '咸香'],
    flavor: ['咸', '香'],
    heat: 1,
    popularity: 9856,
    coverImage: '/images/foods/food-01-cover.jpg',
    images: ['/images/foods/food-01-cover.jpg', '/images/foods/food-04-grilled-fish.jpg'],
    story:
      '湘西腊肉是土家族的传统美食，已有千年历史。每年腊月，土家族人将新鲜猪肉用食盐、花椒、白酒腌制后，悬挂于火塘上方，利用日常烧火做饭产生的烟气慢慢熏烤。经过至少30天的烟熏，腊肉色泽金黄、肉质紧实，带有独特的烟熏香气。在湘西山区，腊肉不仅是日常食物，更是过年待客的上品，承载着土家族人民对美好生活的向往。',
    ingredients: ['新鲜五花肉', '食盐', '花椒', '白酒', '橘皮（增香）'],
    steps: [
      '选用新鲜五花肉，切成长条约30cm × 5cm',
      '用食盐、花椒、白酒均匀涂抹，腌制7天',
      '取出晾干表面水分（约2-3天）',
      '悬挂于火塘上方，用松柏枝、橘皮等慢火烟熏30天以上',
      '熏制好的腊肉外表金黄，切片后可直接炒食或蒸食',
    ],
    nutrition: { calories: '320千卡/100g', protein: '18g', fat: '28g' },
    shops: [
      { name: '古城腊肉坊', address: '凤凰古城东正街12号', avgPrice: 45 },
      { name: '土家老腊味', address: '张家界市永定区解放路88号', avgPrice: 38 },
    ],
  },
  {
    id: 2,
    name: '苗家酸汤鱼',
    category: 'main',
    tags: ['苗族', '酸辣', '招牌菜'],
    flavor: ['酸', '辣'],
    heat: 3,
    popularity: 11230,
    coverImage: '/images/foods/food-02-spicy-fish.jpg',
    images: ['/images/foods/food-02-spicy-fish.jpg', '/images/foods/food-03-fish-soup.jpg'],
    story:
      '苗家酸汤鱼是湘西苗族最具代表性的美食。苗族人常说"三天不吃酸，走路打蹿蹿"，足见酸汤在苗族饮食文化中的重要地位。酸汤分为红酸汤（番茄发酵）和白酸汤（米汤发酵）两种，苗家人用特制的酸汤为底，放入新鲜河鱼，配以木姜子、辣椒等调料，酸辣开胃、鱼肉鲜嫩。这道菜不仅是日常美食，更是苗族节日、婚宴上必不可少的大菜。',
    ingredients: ['新鲜河鱼（鲤鱼/草鱼）', '红酸汤', '番茄', '木姜子', '青椒', '小米辣', '姜蒜'],
    steps: [
      '将鱼宰杀洗净，两面划刀，用料酒和姜腌制15分钟',
      '锅中倒入红酸汤煮沸，加入番茄块煮出红油',
      '放入整条鱼，大火煮5分钟后转中火',
      '加入木姜子、青椒、小米辣调味',
      '煮至鱼肉熟透，撒上葱花和香菜即可出锅',
    ],
    nutrition: { calories: '180千卡/100g', protein: '22g', fat: '9g' },
    shops: [
      { name: '苗家酸汤鱼馆', address: '凤凰古城虹桥中路56号', avgPrice: 68 },
      { name: '阿妹酸汤鱼', address: '吉首市团结东路32号', avgPrice: 55 },
    ],
  },
  {
    id: 3,
    name: '血粑鸭',
    category: 'main',
    tags: ['凤凰名菜', '糯米', '香辣'],
    flavor: ['鲜', '辣'],
    heat: 3,
    popularity: 8720,
    coverImage: '/images/foods/food-04-grilled-fish.jpg',
    images: ['/images/foods/food-04-grilled-fish.jpg', '/images/foods/food-07-spicy-bowl.jpg'],
    story:
      '血粑鸭是凤凰古城的一道传统名菜，以血粑和鸭肉为主料。血粑是湘西地区的独特食品——将新鲜鸭血与浸泡好的糯米混合，灌入肠衣蒸熟后切片。当鸭血糯米粑遇上本地麻鸭，在锅中慢火焖煮，鸭肉的鲜香与血粑的软糯完美融合，成为凤凰古城最具代表性的美食之一。这道菜承载着湘西人民的生活智慧——物尽其用，化平凡为神奇。',
    ingredients: ['本地麻鸭', '糯米', '新鲜鸭血', '干辣椒', '花椒', '姜蒜', '青红椒'],
    steps: [
      '糯米提前浸泡4小时，与新鲜鸭血混合均匀',
      '将鸭血糯米灌入肠衣，蒸40分钟至熟透，切片备用',
      '麻鸭剁块焯水去腥，捞出沥干',
      '锅中放油，爆香姜蒜、干辣椒、花椒',
      '放入鸭块翻炒至表面金黄，加水和调料焖煮30分钟',
      '加入血粑片继续焖煮10分钟，至汤汁浓稠即可',
    ],
    nutrition: { calories: '280千卡/100g', protein: '20g', fat: '18g' },
    shops: [
      { name: '凤凰血粑鸭老店', address: '凤凰古城东正街88号', avgPrice: 78 },
      { name: '沱江人家', address: '凤凰古城沱江镇北门码头旁', avgPrice: 65 },
    ],
  },
  {
    id: 4,
    name: '米豆腐',
    category: 'snack',
    tags: ['芙蓉镇', '小吃', '刘晓庆'],
    flavor: ['清淡', '鲜'],
    heat: 1,
    popularity: 7650,
    coverImage: '/images/foods/food-05-soup-bowl.jpg',
    images: ['/images/foods/food-05-soup-bowl.jpg', '/images/foods/food-06-noodles.jpg'],
    story:
      '米豆腐是湘西地区最常见的传统小吃，以大米为原料，经浸泡、磨浆、煮制、冷却而成，口感滑嫩爽口。芙蓉镇的米豆腐因电影《芙蓉镇》中刘晓庆饰演的胡玉音卖米豆腐而名扬天下。如今在芙蓉镇的青石板老街上，"刘晓庆米豆腐店"依然是最受欢迎的打卡地。一碗米豆腐配上一碟酸豆角、辣椒酱，就是湘西人最熟悉的家常味道。',
    ingredients: ['大米', '石灰水（食用）', '酸豆角', '辣椒酱', '蒜蓉', '葱花', '生抽'],
    steps: [
      '大米浸泡6小时以上，磨成米浆',
      '加入适量食用石灰水搅拌均匀',
      '将米浆倒入锅中，中小火加热并不停搅拌',
      '煮至浓稠透明状，倒入模具冷却定型',
      '切块装碗，配以酸豆角、辣椒酱、蒜蓉、葱花等佐料',
    ],
    nutrition: { calories: '80千卡/100g', protein: '2g', fat: '0.5g' },
    shops: [
      { name: '刘晓庆米豆腐店', address: '芙蓉镇青石板老街15号', avgPrice: 10 },
      { name: '古镇米豆腐', address: '凤凰古城虹桥附近', avgPrice: 8 },
    ],
  },
  {
    id: 5,
    name: '姜糖',
    category: 'snack',
    tags: ['凤凰特产', '手工', '姜味'],
    flavor: ['甜', '辣'],
    heat: 1,
    popularity: 8230,
    coverImage: '/images/foods/food-06-noodles.jpg',
    images: ['/images/foods/food-06-noodles.jpg'],
    story:
      '姜糖是凤凰古城最具代表性的特产之一，将生姜与麦芽糖结合，经过反复拉扯、折叠，制成酥脆可口的糖果。在凤凰古城的街头，经常可以看到手工艺人现场拉制姜糖——将温热的糖团挂在铁钩上反复拉扯，糖体由深褐色逐渐变成金黄色，过程极具观赏性。姜糖不仅是美味零食，还具有暖胃驱寒的养生功效。',
    ingredients: ['生姜', '麦芽糖', '白砂糖', '芝麻'],
    steps: [
      '生姜榨汁过滤，取姜汁备用',
      '将麦芽糖和白砂糖放入锅中，加热融化',
      '加入姜汁，继续熬煮至适当浓度',
      '将糖浆倒在石板上冷却至温热',
      '反复拉扯糖团至金黄色，拉成细条后剪成小段',
    ],
    nutrition: { calories: '380千卡/100g', protein: '0.5g', fat: '1g' },
    shops: [
      { name: '老凤凰姜糖坊', address: '凤凰古城东正街45号', avgPrice: 25 },
      { name: '沈从文姜糖铺', address: '凤凰古城文化广场旁', avgPrice: 20 },
    ],
  },
  {
    id: 6,
    name: '社饭',
    category: 'festival',
    tags: ['土家族', '节庆美食', '传统'],
    flavor: ['咸', '香'],
    heat: 0,
    popularity: 6210,
    coverImage: '/images/foods/food-07-spicy-bowl.jpg',
    images: ['/images/foods/food-07-spicy-bowl.jpg'],
    story:
      '社饭是土家族的传统节庆美食，源于古代的"春社"祭祀活动。每年农历二月初二"社日"，土家族家家户户都要做社饭，祭祀土地神，祈求风调雨顺、五谷丰登。社饭以糯米为主料，加入腊肉丁、野葱、蒿菜等配料，用柴火蒸制而成。如今，社饭已从祭祀食品演变为土家族日常生活中的特色主食。',
    ingredients: ['糯米', '腊肉', '野葱', '蒿菜', '花生', '豆腐干'],
    steps: [
      '糯米提前浸泡4小时',
      '腊肉切丁，野葱和蒿菜洗净切碎',
      '将所有配料与糯米混合均匀，加适量盐调味',
      '放入蒸笼，大火蒸40分钟至糯米熟透',
      '出锅后拌匀即可食用',
    ],
    nutrition: { calories: '220千卡/100g', protein: '8g', fat: '6g' },
    shops: [
      { name: '土家社饭馆', address: '张家界武陵源区军邸路18号', avgPrice: 15 },
    ],
  },
  {
    id: 7,
    name: '油茶',
    category: 'drink',
    tags: ['苗族', '待客', '咸味'],
    flavor: ['咸', '香'],
    heat: 0,
    popularity: 5890,
    coverImage: '/images/foods/food-08-indonesian-fish.jpg',
    images: ['/images/foods/food-08-indonesian-fish.jpg'],
    story:
      '油茶是湘西苗族的传统饮品，也是苗家人待客的最高礼节。制作油茶需要"三道汤"：第一道用茶叶和姜捶打熬煮，第二道加入花生、阴米等配料，第三道调味。苗家人待客时，油茶要喝三碗——第一碗解渴，第二碗品味，第三碗祝福。一碗热腾腾的油茶，不仅暖身驱寒，更承载着苗族人民的热情好客。',
    ingredients: ['茶叶', '生姜', '花生', '阴米', '炒米', '食盐'],
    steps: [
      '茶叶和生姜放入擂钵中捶打成泥',
      '锅中放油，将茶叶姜泥炒香',
      '加入清水煮沸，滤出茶汤',
      '碗中放入花生、炒米、阴米等配料',
      '冲入滚烫的茶汤，加盐调味即可',
    ],
    nutrition: { calories: '60千卡/碗', protein: '3g', fat: '2g' },
    shops: [
      { name: '苗家油茶坊', address: '凤凰古城沱江镇老菜街23号', avgPrice: 12 },
    ],
  },
  {
    id: 8,
    name: '糍粑',
    category: 'festival',
    tags: ['土家族', '年节', '糯米'],
    flavor: ['甜', '糯'],
    heat: 0,
    popularity: 7020,
    coverImage: '/images/foods/food-01-cover.jpg',
    images: ['/images/foods/food-01-cover.jpg'],
    story:
      '糍粑是土家族过年的必备食品。每年腊月，土家族人将糯米蒸熟后放入石臼中，用木槌反复捶打至黏稠，再捏成圆饼状。打糍粑是土家族过年最热闹的集体活动——男女老少围在一起，轮流挥舞木槌，一边打糍粑一边唱歌，场面欢乐祥和。糍粑可煎可烤可煮，配上白糖或蜂蜜，是湘西人最温暖的美食记忆。',
    ingredients: ['糯米', '白糖', '芝麻', '黄豆粉'],
    steps: [
      '糯米提前浸泡8小时',
      '将糯米放入蒸笼蒸熟（约30分钟）',
      '趁热将糯米饭放入石臼中',
      '用木槌反复捶打至黏稠无颗粒',
      '手上抹油，将糯米团分成小剂子，压成圆饼',
      '撒上芝麻或裹上黄豆粉即可食用',
    ],
    nutrition: { calories: '250千卡/100g', protein: '3g', fat: '0.5g' },
    shops: [
      { name: '土家糍粑店', address: '张家界市武陵源区溪布街9号', avgPrice: 10 },
    ],
  },
]
