export const heritageItems = [
  {
    id: 'miao-silver',
    name: '苗族银饰锻制技艺',
    category: 'metalwork',
    image: '/images/culture/culture-01-miao-costume.jpg',
    summary: '国家级非遗，苗族银饰以大、重、多为美，一套完整盛装重达十多公斤。',
    level: '国家级',
  },
  {
    id: 'xilan-kapu',
    name: '土家织锦（西兰卡普）',
    category: 'textile',
    image: '/images/culture/culture-02-miao-women.jpg',
    summary: '国家级非遗，土家族传统织锦，图案多达200余种，色彩鲜艳。',
    level: '国家级',
  },
  {
    id: 'miao-embroidery',
    name: '苗族刺绣',
    category: 'textile',
    image: '/images/culture/culture-03-miao-headdress.jpg',
    summary: '苗族妇女世代传承的手工技艺，以针代笔、以线为墨。',
    level: '国家级',
  },
  {
    id: 'batik',
    name: '蜡染技艺',
    category: 'textile',
    image: '/images/culture/culture-04-traditional-dress.jpg',
    summary: '苗族和土家族共有的传统印染工艺，独特的"冰纹"效果浑然天成。',
    level: '国家级',
  },
  {
    id: 'hand-waving-dance',
    name: '土家族摆手舞',
    category: 'dance',
    image: '/images/culture/culture-miao.jpg',
    summary: '土家族最具代表性的民间舞蹈，粗犷有力、节奏鲜明。',
    level: '国家级',
  },
  {
    id: 'bamboo-weaving',
    name: '湘西竹编',
    category: 'craft',
    image: '/images/culture/culture-04-traditional-dress.jpg',
    summary: '以精细著称，篾片薄如蝉翼、篾丝细如发丝。',
    level: '省级',
  },
  {
    id: 'miao-drum',
    name: '苗鼓艺术',
    category: 'music',
    image: '/images/culture/culture-03-miao-headdress.jpg',
    summary: '苗族鼓舞是湘西苗族最古老的传统艺术形式，鼓点雄浑激昂。',
    level: '省级',
  },
  {
    id: 'tujia-song',
    name: '土家族山歌',
    category: 'music',
    image: '/images/culture/culture-02-miao-women.jpg',
    summary: '土家族人民即兴创作的山歌，内容涵盖劳动、爱情、历史传说。',
    level: '省级',
  },
]

export const HERITAGE_CATEGORY_MAP = {
  all: '全部',
  metalwork: '金属工艺',
  textile: '织染绣',
  dance: '传统舞蹈',
  craft: '手工技艺',
  music: '传统音乐',
}
